export type ProjectStatus = "pending" | "live" | "graduated" | "failed";
export type DestinationType = "creator" | "liquidity" | "project_treasury" | "protocol_treasury" | "launch_protocol_fee" | "community";

type Table<Row> = { Row: Row; Insert: Record<string, unknown>; Update: Record<string, unknown> };
type RawAmountViews = {
  fee_routing_events_exact: Table<{ id:string; project_id:string; chain_id:number; tx_hash:string; log_index:number; block_number:number; block_timestamp:string|null; destination_type:DestinationType; destination_address:string|null; token_address:string|null; raw_amount:string; token_decimals:number|null; pool_id:string|null; currency:string|null; gross_amount_raw:string|null; block_hash:string|null; canonical:boolean; created_at:string }>;
  fee_accrual_events_exact: Table<{ id:string; project_id:string; chain_id:number; pool_id:string; currency:string; tx_hash:string; log_index:number; block_number:number; block_hash:string; block_timestamp:string|null; swapper_address:string; raw_amount:string; canonical:boolean; created_at:string }>;
  fee_allocation_events_exact: Table<{ id:string; project_id:string; chain_id:number; pool_id:string; currency:string; tx_hash:string; log_index:number; block_number:number; block_hash:string; block_timestamp:string|null; gross_amount_raw:string; protocol_allocation_raw:string; creator_allocation_raw:string; project_treasury_allocation_raw:string; community_allocation_raw:string; liquidity_allocation_raw:string; canonical:boolean; created_at:string }>;
  fee_claim_events_exact: Table<{ id:string; project_id:string; chain_id:number; pool_id:string; currency:string; recipient_address:string; recipient_type:"creator"|"project_treasury"|"community"|"protocol_treasury"|"project_recipient"; tx_hash:string; log_index:number; block_number:number; block_hash:string; block_timestamp:string|null; raw_amount:string; canonical:boolean; created_at:string }>;
  protocol_launch_fee_events_exact: Table<{ id:string; project_id:string; chain_id:number; pool_id:string; token_address:string; creator_address:string; tx_hash:string; log_index:number; block_number:number; block_hash:string; block_timestamp:string|null; raw_amount:string; canonical:boolean; created_at:string }>;
  protocol_launch_fee_claim_events_exact: Table<{ id:string; chain_id:number; recipient_address:string; tx_hash:string; log_index:number; block_number:number; block_hash:string; block_timestamp:string|null; raw_amount:string; canonical:boolean; created_at:string }>;
  liquidity_credit_events_exact: Table<{ id:string; project_id:string; chain_id:number; pool_id:string; currency:string; tx_hash:string; log_index:number; block_number:number; block_hash:string; block_timestamp:string|null; raw_amount:string; canonical:boolean; created_at:string }>;
  projects_raw_amounts_exact: Table<{ id:string; total_supply_raw:string|null; seed_token_amount_raw:string|null; seed_quote_amount_raw:string|null; sqrt_price_x96:string|null }>;
  // The already-applied remote view retains the legacy project metric alias
  // `treasury_fees_raw`; routing configuration/events use explicit project_treasury names.
  project_metrics_raw_amounts_exact: Table<{ id:string; project_id:string; total_fees_raw:string|null; creator_fees_raw:string|null; liquidity_fees_raw:string|null; treasury_fees_raw:string|null; community_fees_raw:string|null; protocol_swap_fees_raw:string|null; launch_protocol_fees_raw:string|null }>;
  metric_snapshots_raw_amounts_exact: Table<{ id:string; project_id:string; total_fees_raw:string|null }>;
  project_fee_distribution_summary: Table<{ project_id:string; protocol_raw:string; creator_raw:string; liquidity_raw:string; project_treasury_raw:string; community_raw:string }>;
};

export type Database = {
  public: {
    Tables: {
      // Raw numeric(78,0) columns in base tables are unsafe to read via PostgREST
      // (they arrive as JS numbers). Application reads must use *_exact views.
      projects: Table<{ id:string; chain_id:number; token_address:string; creator_address:string; name:string; symbol:string; description:string|null; logo_url:string|null; website_url:string|null; x_url:string|null; telegram_url:string|null; discord_url:string|null; status:ProjectStatus; launch_tx_hash:string|null; launch_block_number:number|null; launched_at:string|null; pool_id:string|null; quote_asset:string|null; total_supply_raw:number|null; seed_token_amount_raw:number|null; seed_quote_amount_raw:number|null; sqrt_price_x96:number|null; lp_fee:number|null; launch_block_hash:string|null; canonical:boolean; created_at:string; updated_at:string; metadata_updated_at:string|null; verified:boolean; is_hidden:boolean }>;
      fee_configs: Table<{ id:string; project_id:string; creator_bps:number; liquidity_bps:number; project_treasury_bps:number; community_bps:number; creator_destination:string|null; project_treasury_destination:string|null; community_destination:string|null; liquidity_strategy_address:string|null; config_tx_hash:string|null; block_number:number|null; configured_at:string|null; is_immutable:boolean; canonical:boolean; created_at:string }>;
      project_metrics: Table<{ id:string; project_id:string; price_usd:string|null; market_cap_usd:string|null; volume_24h_usd:string|null; liquidity_usd:string|null; holder_count:number|null; total_fees_raw:number|null; creator_fees_raw:number|null; liquidity_fees_raw:number|null; treasury_fees_raw:number|null; community_fees_raw:number|null; protocol_swap_fees_raw:number|null; launch_protocol_fees_raw:number|null; last_indexed_block:number|null; calculated_at:string|null; updated_at:string }>;
      fee_routing_events: Table<{ id:string; project_id:string; chain_id:number; tx_hash:string; log_index:number; block_number:number; block_timestamp:string|null; destination_type:DestinationType; destination_address:string|null; token_address:string|null; raw_amount:number; token_decimals:number|null; pool_id:string|null; currency:string|null; gross_amount_raw:number|null; block_hash:string|null; canonical:boolean; created_at:string }>;
      fee_allocation_events: Table<{ id:string; project_id:string; chain_id:number; pool_id:string; currency:string; tx_hash:string; log_index:number; block_number:number; block_hash:string; block_timestamp:string|null; gross_amount_raw:number; protocol_allocation_raw:number; creator_allocation_raw:number; project_treasury_allocation_raw:number; community_allocation_raw:number; liquidity_allocation_raw:number; canonical:boolean; created_at:string }>;
      fee_claim_events: Table<{ id:string; project_id:string; chain_id:number; pool_id:string; currency:string; recipient_address:string; recipient_type:"creator"|"project_treasury"|"community"|"protocol_treasury"|"project_recipient"; tx_hash:string; log_index:number; block_number:number; block_hash:string; block_timestamp:string|null; raw_amount:number; canonical:boolean; created_at:string }>;
      protocol_launch_fee_events: Table<{ id:string; project_id:string; chain_id:number; pool_id:string; token_address:string; creator_address:string; tx_hash:string; log_index:number; block_number:number; block_hash:string; block_timestamp:string|null; raw_amount:number; canonical:boolean; created_at:string }>;
      protocol_launch_fee_claim_events: Table<{ id:string; chain_id:number; recipient_address:string; tx_hash:string; log_index:number; block_number:number; block_hash:string; block_timestamp:string|null; raw_amount:string; canonical:boolean; created_at:string }>;
      fee_accrual_events: Table<{ id:string; project_id:string; chain_id:number; pool_id:string; currency:string; tx_hash:string; log_index:number; block_number:number; block_hash:string; block_timestamp:string|null; swapper_address:string; raw_amount:number; canonical:boolean; created_at:string }>;
      liquidity_credit_events: Table<{ id:string; project_id:string; chain_id:number; pool_id:string; currency:string; tx_hash:string; log_index:number; block_number:number; block_hash:string; block_timestamp:string|null; raw_amount:number; canonical:boolean; created_at:string }>;
      launches: Table<{ id:string; project_id:string; creator_address:string; factory_address:string|null; token_address:string|null; pool_address:string|null; pool_id:string|null; quote_asset:string|null; pair_token_address:string|null; launch_tx_hash:string|null; launch_block_number:number|null; launch_timestamp:string|null; graduation_tx_hash:string|null; graduated_at:string|null; canonical:boolean; created_at:string; updated_at:string }>;
      indexer_state: Table<{ id:string; chain_id:number; contract_address:string; last_processed_block:number; last_processed_block_hash:string|null; updated_at:string }>;
      project_metadata: Table<{ id:string; project_id:string; description:string|null; logo_url:string|null; banner_url:string|null; website_url:string|null; x_url:string|null; telegram_url:string|null; discord_url:string|null; updated_by_wallet:string|null; updated_at:string }>;
    };
    Views: RawAmountViews;
    Functions: { mark_chain_events_noncanonical: { Args: { p_chain_id:number; p_from_block:number }; Returns:undefined } };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
