"use client";

import Link from "next/link";
import Image from "next/image";
import { DEFAULT_SPLIT, type Token } from "../data/mock";
import { Icon } from "./icons";
import { AppFooter, AppHeader, StatusBadge } from "./shell";
import { FeeHero } from "./hero/fee-hero";
import { Donut, Reveal, RouteCore } from "./visuals";

export function HomePage({ tokens }: { tokens: Token[] }) {
  return <div className="home-page"><AppHeader /><main>
    <FeeHero />
    <section className="story-section story-origin" id="origin"><div className="section-shell story-grid"><Reveal className="story-copy"><span className="eyebrow">Scroll 01 / Origin</span><h2>Official pool swaps<br />generate a fee.</h2><h3>Where should<br />it go?</h3><p>SPLIT applies its 1% protocol fee only to the official pool created and registered by its factory. Other pools and venues are outside SPLIT fee accounting.</p></Reveal><Reveal delay={160} className="origin-machine"><div className="machine-funnel" /><span className="falling-fee" /><RouteCore compact /></Reveal></div></section>
    <section className="story-section story-rules" id="logic"><div className="section-shell rules-wrap"><Reveal className="story-copy centered"><span className="eyebrow">Scroll 02 / Routing logic</span><h2>You set<br />the rules.</h2><p>Choose how fees are distributed before your token launches.</p></Reveal><Reveal delay={100} className="allocation-rule-card glass-panel"><span className="eyebrow">Illustration · $1.00 collected fee · bars show total-fee share</span><div className="rule-row protocol-rule"><div><strong>Protocol Treasury</strong><strong>10% of total fee</strong></div><div className="fee-track"><span style={{ "--bar-target": "10%", background: "#b98aff" } as React.CSSProperties} /></div><small>$0.10 of $1.00 collected</small></div>{DEFAULT_SPLIT.map((item) => { const effectiveShare = item.value * 0.9; const amount = effectiveShare / 100; return <div className="rule-row" key={item.key}><div><strong>{item.label}</strong><strong className="rule-effective">{effectiveShare}% of total fee<small>{item.value}% of project portion</small></strong></div><div className="fee-track"><span style={{ "--bar-target": `${effectiveShare}%`, background: item.color } as React.CSSProperties} /></div><small>${amount.toFixed(2)} of $1.00 collected</small></div>; })}<div className="rule-total"><span>Total fee accounted for</span><strong>100% · $1.00</strong></div></Reveal></div></section>
    <section className="story-section story-execution"><div className="section-shell story-grid"><Reveal className="story-copy"><span className="eyebrow">Scroll 03 / Execution</span><h2>Split does<br />the rest.</h2><p>Trades accrue SPLIT fees first. Anyone can trigger a separate flush, which routes the accrued balance using the immutable allocation.</p><div className="destination-grid">{DEFAULT_SPLIT.map((item, index) => <div className="destination-card" key={item.key}><Icon name={index === 0 ? "wallet" : index === 1 ? "layers" : index === 2 ? "chart" : "globe"} /><span className="destination-pulse" style={{ background: item.color }} /><strong>{item.label}</strong><small>{["Reward the originator", "Reserve for pool liquidity", "Build the reserve", "Fund what matters"][index]}</small></div>)}</div></Reveal><Reveal delay={160} className="stream-map"><span className="stream-source" />{DEFAULT_SPLIT.map((item, index) => { const duration = 3.3 - index * .34; const delay = index * -.65; return <span key={item.key} className={`stream-branch stream-branch-${index + 1}`} style={{ "--stream-color": item.color, "--flow-size": `${Math.max(3, item.value / 8)}px`, "--flow-duration": `${duration}s`, "--flow-delay": `${delay}s`, "--flow-delay-2": `${delay + duration / 3}s`, "--flow-delay-3": `${delay + duration * 2 / 3}s` } as React.CSSProperties}><span className="stream-flow" aria-hidden="true"><em /><em /><em /></span><i /><small>{item.label}<b>{item.value}%</b></small></span>; })}</Reveal></div></section>
    <section className="story-section story-launch" id="launch"><div className="section-shell launch-wrap"><Reveal className="story-copy launch-copy"><span className="eyebrow">Scroll 04 / Launch</span><h2>Launch with<br />purpose.</h2><p>Your token launches with its fee distribution already defined.</p></Reveal><Reveal delay={120} className="token-prototype glass-panel"><div className="token-sphere" /><h3>Your Token</h3><span>$TKN</span><dl><div><dt>Token</dt><dd>ERC-20 Compatible</dd></div><div><dt>Pair</dt><dd>TKN/ETH</dd></div><div><dt>Fee Split</dt><dd>40/30/20/10</dd></div><div><dt>Network</dt><dd>Robinhood Chain</dd></div></dl><RouteCore compact /><Link href="/launch/details" className="button button-primary">Create Token</Link></Reveal></div></section>
    <section className="story-section story-discovery" id="explore"><div className="section-shell"><Reveal className="story-copy"><span className="eyebrow">Scroll 05 / Discovery</span><h2>See where<br />the fees go.</h2><p>Only launches confirmed by the SPLIT factory are listed. No launch data is simulated.</p></Reveal><div className="home-token-grid">{tokens.map((token, index) => <Reveal delay={index * 70} key={token.address} className="mini-token-card glass-panel"><Link href={`/token/${token.address}`}><div className="mini-token-head"><span className="token-dot" style={{ background: token.color }}>{token.logoUrl ? <Image src={token.logoUrl} width={22} height={22} unoptimized alt="" /> : null}</span><div><strong>{token.name}</strong><small>${token.ticker}</small></div><StatusBadge status={token.status} /></div><div className="mini-stats"><span>Market cap<strong>{token.marketCap}</strong></span><span>Volume<strong>{token.volume}</strong></span></div><Donut allocations={token.split} /></Link></Reveal>)}</div>{!tokens.length ? <p>No canonical launches are indexed yet.</p> : null}<Link className="button button-outline discovery-cta" href="/explore">Explore indexed launches <Icon name="arrow" /></Link></div></section>
    <section className="home-finale"><Reveal><RouteCore /><h2><span>One stream in.</span><br />Any number of destinations.</h2><strong className="finale-word">SPLIT</strong><p>Give every fee a destination.</p><Link href="/launch/details" className="button button-primary">Launch on SPLIT <Icon name="arrow" /></Link></Reveal></section>
  </main><AppFooter /></div>;
}
